version: '2'

services:
  diaspora:
    build:
      context: .
    container_name: diaspora
    environment:
        ENVIRONMENT_URL: https://diaspora
        ENVIRONMENT_REDIS: redis://redis
        SSH_AUTH_SOCK:  "/ssh-agent"
    links:
      - postgres
      - redis
    volumes:
      - ./ssl:/etc/certs
      - $SSH_AUTH_SOCK:/ssh-agent # Forward local machine SSH key to docker
    ports:
      - "80:80"
      - "443:443"
    networks:
      - default
  postgres:
    image: postgres:9
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: "mysecretpassword"
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - //var/lib/postgresql/data:/var/lib/postgresql/data
    networks:
      - default
  redis:
    image: redis:3
    container_name: redis
