version: '2'

services:
  diaspora:
    build:
      context: .
    container_name: diaspora
    environment:
        ENVIRONMENT_URL: "https://${DIASPORA_HOST}"
        ENVIRONMENT_REDIS: redis://redis
        SSH_AUTH_SOCK:  "/ssh-agent"
    links:
      - postgres
      - redis
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /data/diaspora/uploads:/home/diaspora/diaspora/public/uploads
    ports:
      - "80:80"
      - "443:443"
    networks:
      - default
  postgres:
    image: postgres:9
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
    networks:
      - default
  redis:
    image: redis:3
    container_name: redis
