version: '2'

services:
  diaspora:
    build:
      context: .
    container_name: diaspora
    hostname: "${DIASPORA_HOST}"
    environment:
        ENVIRONMENT_URL: "https://${DIASPORA_HOST}"
        ENVIRONMENT_REDIS: redis://redis
        SETTINGS_ENABLE_REGISTRATIONS: "false"
        SETTINGS_AUTOFOLLOW_ON_JOIN_USER: DMCritCircle@pod.cudigital.media
        MAIL_ENABLE: "true"
        MAIL_SENDER_ADDRESS: no-reply@pod.cudigital.media
        MAIL_METHOD: smtp
        MAIL_SMTP_HOST: smtp
        MAIL_SMTP_PORT: 25
        MAIL_SMTP_AUTHENTICATION: none
        MAIL_SMTP_STARTTLS_AUTO: "false"
        MAIL_SMTP_DOMAIN: "${DIASPORA_HOST}"
        SSH_AUTH_SOCK:  "/ssh-agent"
    links:
      - postgres
      - redis
      - smtp
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /data/diaspora/uploads:/home/diaspora/diaspora/public/uploads
    ports:
      - "80:80"
      - "443:443"
    networks:
      - default
  postgres:
    image: postgres:9
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
    networks:
      - default
  redis:
    image: redis:3
    container_name: redis
  smtp:
    image: tianon/exim4:latest
    container_name: exim4
    hostname: "${DIASPORA_HOST}"
    volumes:
      - /etc/mailname:/etc/mailname:ro
